name: CI (minimal)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (root + workspaces)
        run: npm ci

      - name: Lint (all workspaces, if present)
        run: npm run --workspaces --if-present lint || true

      - name: Build (all workspaces, if present)
        run: npm run --workspaces --if-present build
